- include: install.yml
  when: not skip_install

- name: Update config (0.8.x)
  template: src=config.toml dest=/opt/influxdb/shared/config.toml
  when: influxdb_version|version_compare('0.9', '<')
  notify:
    - restart influxdb

- name: Update config (0.9.x)
  template: src=influxdb.conf dest=/etc/opt/influxdb/influxdb.conf
  when: influxdb_version|version_compare('0.9', '>=')
  notify:
    - restart influxdb
    
- name: Copy ssl key
  copy: dest={{influxdb_ssl_certificate}} src={{influxdb_ssl_certificate_src}} owner=influxdb group=root mode=0440
  when: influxdb_ssl_certificate_src is defined
  notify:
    - restart influxdb

- meta: flush_handlers

- name: Enable influxdb
  service: name=influxdb state=started enabled=yes

- name: wait for influxdb port
  wait_for: port={{influxdb_client_port}} host={{influxdb_bind_address |replace('0.0.0.0', '127.0.0.1')}} state=started timeout=30
  ignore_errors: yes
  register: first_wait

- name: restart if clustering failed to connect
  service: name=influxdb state=restarted
  when: first_wait|failed

- name: 2nd wait for influxdb port
  wait_for: port={{influxdb_client_port}} host={{influxdb_bind_address |replace('0.0.0.0', '127.0.0.1')}} state=started timeout=30
  when: first_wait|failed
