- include: install.yml
  when: not skip_install

- name: Update config (0.8.x)
  template: src=config.toml dest=/opt/influxdb/shared/config.toml
  when: influxdb.version|search("0\.8\..*")
  notify:
    - restart influxdb

- name: Update config (0.9.x)
  template: src=influxdb.conf dest=/etc/opt/influxdb/influxdb.conf
  when: influxdb.version|search("0\.9\..*")
  notify:
    - restart influxdb
    
- name: Copy ssl key
  copy: dest={{influxdb_ssl_certificate}} src={{influxdb_ssl_certificate_src}} owner=influxdb group=root mode=0440
  when: influxdb_ssl_certificate_src is defined
  notify:
    - restart influxdb

- meta: flush_handlers

- name: Enable influxdb
  service: name=influxdb state=started enabled=yes

- name: wait for influxdb port
  wait_for: port={{influxdb_client_port}} state=started timeout=30

