- include: install.yml
  when: not skip_install

- name: Update config
  template: src=config.toml dest=/opt/influxdb/shared/config.toml
  notify:
    - restart influxdb
    
- name: Copy ssl key
  copy: dest={{influxdb_ssl_certificate}} src={{influxdb_ssl_certificate_src}} owner=influxdb group=root mode=0440
  when: influxdb_ssl_certificate_src is defined
  notify:
    - restart influxdb

- meta: flush_handlers

- name: Enable influxdb
  service: name=influxdb state=started enabled=yes

- name: wait for influxdb port
  wait_for: port={{influxdb_client_port}} host={{influxdb_bind_address |replace('0.0.0.0', '127.0.0.1')}} state=started timeout=30
