---

- name: Fetch package
  get_url:
    url: "http://s3.amazonaws.com/influxdb/influxdb-{{ influxdb_version }}.x86_64.rpm"
    dest: "/root/influxdb-{{ influxdb_version }}.x86_64.rpm"
  register: get_url_result
  until: get_url_result.state == 'file'
  retries: 5
  delay: 1

- name: Install package
  yum:
    name: "/root/influxdb-{{ influxdb_version }}.x86_64.rpm"
    state: present
