---
- name: Enable and start influxdb
  service: name=influxdb state=started enabled=yes

- name: wait for influxdb port
  wait_for: port={{influxdb_client_port}} host={{influxdb_bind_address |replace('0.0.0.0', '127.0.0.1')}} state=started timeout=30
  ignore_errors: yes
  register: first_wait
