---
- name: Enable and start influxdb
  service:
    name: influxdb
    enabled: yes

- name: wait for influxdb port
  wait_for:
    port: "{{ influxdb_client_port }}"
    host: "{{ influxdb_bind_address | default('127.0.0.1') }}"
    state: started
    timeout: 180