---
- name: Restart influxdb
  systemd:
    name: influxdb
    state: restarted
    daemon_reload: yes

- name: Restart influxdb-relay
  systemd:
    name: influxdbrelay
    state: restarted
    daemon_reload: yes
